version: '3'

volumes:
  ipfs:
    labels: 
      - "${PROJECT}=ipfs"

services:
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    container_name: ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs:/data/ipfs
      - ./metadata.json:/home/metadata.json
      - ./images:/home/images

  redis:
    image: redis:6.0.1-alpine
    container_name: redis
    ports:
      - "6379:6379"