version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        - GIT_COMMIT=e37ef57
    container_name: api
    ports:
      - "8088:8088"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./card-metadata.csv:/home/card-metadata.csv
      - ./mintcodes.csv:/home/mintcodes.csv

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
      args:
        - GIT_COMMIT=e37ef57
    container_name: worker
    depends_on: 
      - db
      - redis
    env_file:
      - .env
