version: '3'

volumes:
  uploads:

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        - GIT_COMMIT=8ebee14
    container_name: api
    ports:
      - "8088:8088"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./card-metadata.csv:/usr/src/app/card-metadata.csv
      - ./mintcodes.csv:/usr/src/app/mintcodes.csv
      - ./mirrorcodes.csv:/usr/src/app/mirrorcodes.csv
      - uploads:/usr/src/app/uploads

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
      args:
        - GIT_COMMIT=8ebee14
    container_name: worker
    depends_on: 
      - db
      - redis
    env_file:
      - .env
    volumes:
      - uploads:/usr/src/app/uploads
