version: '3'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  mongo:
    image: mongo:4.4
    volumes:
      - ${NS_MONGO_DATA_DIR:-./mongo-data}:/data/db:cached
    logging: *default-logging

  nightscout:
    image: nightscout/cgm-remote-monitor:latest
    container_name: nightscout
    restart: always
    depends_on:
      - mongo
    logging: *default-logging
    ports:
      - "1337:1337"
    env_file:
      - .nightscout.env
    environment:
      NODE_ENV: production
      TZ: Europe/Berlin
      INSECURE_USE_HTTP: true
      MONGO_CONNECTION: mongodb://mongo:27017/nightscout
      DISPLAY_UNITS: mmol/L
      TIME_FORMAT: 24
      ENABLE: careportal rawbg iob
