version: '3'

volumes:
  ipfs:
    labels: 
      - "${PROJECT}=ipfs"
  data:

services:
  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    container_name: ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs:/data/ipfs
      - ./images:/home/images
      - ./metadata:/home/metadata
      - ./clickmine:/home/clickmine

  redis:
    image: redis:6.0.1-alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:12.2-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      # - ./db/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
      - data:/var/lib/postgresql/data