version: '3'

services:
  ganache:
    image: trufflesuite/ganache-cli:v6.10.1
    container_name: ganache
    ports:
      - "8545:8545"
    command: [
      "--deterministic",
      "--networkId", "5777",
      "--hostname", "0.0.0.0",
      "--accounts", "10",
      "--defaultBalanceEther", "10000",
      "--gasLimit", "10000000",
      "--noVMErrorsOnRPCResponse"
    ]
