version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        - GIT_COMMIT=ff41566
    container_name: api
    depends_on:
      - db
      - redis
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
      args:
        - GIT_COMMIT=ff41566
    container_name: worker
    depends_on: 
      - db
      - redis
    env_file:
      - .env
